### ISSUE TITLE
Is this algorithm supporting polygon ?

### ISSUE THREAD

**Issue by bagusflyer** [emma-k-alexandra/RTree#3]
I'm wondering if your solution support polygon besides points like what Apple's GKRTree does.

**Comment by emma-k-alexandra** [comment]
Yep, when defining your `SpatialObject`, as long as you can define a `minimumBoundingRectangle` around your shape & `distanceSquared` to your `SpatialObject.Point` (which could certainly be a polygon), you'll be able to find the nearest neighbor of your polygon.

**Comment by bagusflyer** [comment]
I think no problem to find the boundingbox for the polygon. But how to define `distanceSquared`? What's your suggestion? Should we use the center of the polygon to calculate?
